### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by morcibacsi** [xuhaojie/WifiBox#1]
Hi,

I am the author of the [PSA VAN-CAN bridge software](https://github.com/morcibacsi/PSAVanCanBridge) which has some similar functionality like you have implemented based on the description. I would have like to take a peek on the source code of your firmware, but unfortunately it seems like it is missing from the repository. Are you planning to upload it?

Best regards, Peter

**Comment by morcibacsi** [comment]
您能否也共享固件代码？

**Comment by xuhaojie** [comment]
> 您能否也共享固件代码？



> Hi,
> 
> I am the author of the [PSA VAN-CAN bridge software](https://github.com/morcibacsi/PSAVanCanBridge) which has some similar functionality like you have implemented based on the description. I would have like to take a peek on the source code of your firmware, but unfortunately it seems like it is missing from the repository. Are you planning to upload it?
> 
> Best regards, Peter
Him
 Which part of the source code do you need?
Because we use different hardware, I'm not sure my source code can help you.

**Comment by morcibacsi** [comment]
Hi, yeah, I know, but I would be interested in the VAN related parts (for my education). I am really curious how you have implemented V2C functionality. To be more precise as I remember the V2C was able to send VAN packets for querying the trip computer data without a VAN controller, I would definitely take a look in that how it was implemented.

**Comment by xuhaojie** [comment]
Please leave your email here or send a email to xuhaojie@hotmail.com, I will send you the source code you need.
